version : '2'

services :
  payara:
    build: payara_server_db
    container_name: amt_project_payara
    restart: always
    ports:
      - "4848:4848"
      - "8080:8080"
    volumes:
      - ./deployments:/opt/payara41/deployments
    links:
      - db

  db:
    image: mysql
    container_name: amt_project_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql

