version : '2'

services :
  payara:
    build: payara_server_db
    container_name: payara
    restart: always
    ports:
      - "4848:4848"
      - "8080:8080"
    volumes:
      - ~/payara:/opt/payara41/deployments
    links:
            - mysql:db

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ~/data:/var/lib/mysql

