USE AMTProjectDatabase;

INSERT INTO tbStatus(statusId, status)
VALUES (0, 'Inactive'),
	   (1, 'Active'),
	   (2, 'HasChangedPassword');
	   
INSERT INTO tbPrivilege(privilegeId, privilege)
VALUES (0, 'User'),
	   (1, 'Administrator');
	   
INSERT INTO tbUser (userLastName, userFirstName, userEmail, userPassword, userAvatar, privilegeId, statusId)
VALUES ('Schar', 'Joel', 'joel.schar@heig-vd.ch', '1000:6e159ff5f267d11c3fb1ce463a6cf455:465e34b808e7e4624f148f9bc74107161be3abca8c3d4160b3511f96eaa283feb1ee7d94650d54cb8f5d6dec37a2b09263b51b51fbba1636d2866d7dde5bcd18', "", 1, 1),
       ('Lederrey', 'Yann', 'yann.lederrey@heig-vd.ch', '1000:6e159ff5f267d11c3fb1ce463a6cf455:465e34b808e7e4624f148f9bc74107161be3abca8c3d4160b3511f96eaa283feb1ee7d94650d54cb8f5d6dec37a2b09263b51b51fbba1636d2866d7dde5bcd18', "", 1, 1),
       ('Neto', 'Patrick', 'patrick.neto@heig-vd.ch', '1000:6e159ff5f267d11c3fb1ce463a6cf455:465e34b808e7e4624f148f9bc74107161be3abca8c3d4160b3511f96eaa283feb1ee7d94650d54cb8f5d6dec37a2b09263b51b51fbba1636d2866d7dde5bcd18', "", 1, 1),
       ('Henriquet', 'Steve', 'steve.henriquet@heig-vd.ch', '1000:6e159ff5f267d11c3fb1ce463a6cf455:465e34b808e7e4624f148f9bc74107161be3abca8c3d4160b3511f96eaa283feb1ee7d94650d54cb8f5d6dec37a2b09263b51b51fbba1636d2866d7dde5bcd18',"", 0, 1),
       ('inactif', 'user', 'user.inactif@heig-vd.ch', '1000:6e159ff5f267d11c3fb1ce463a6cf455:465e34b808e7e4624f148f9bc74107161be3abca8c3d4160b3511f96eaa283feb1ee7d94650d54cb8f5d6dec37a2b09263b51b51fbba1636d2866d7dde5bcd18', "", 0, 0);


INSERT INTO tbProject (projectName, projectDescrition, projectCreationDate, APIKey, APISecret)
VALUES ('Lorem Ipsum', 'Sed laeditur hic coetuum magnificus splendor levitate paucorum incondita, ubi nati sunt non reputantium, sed tamquam indulta licentia vitiis ad errores lapsorum ac lasciviam. ut enim Simonides lyricus docet, beate perfecta ratione vieturo ante alia patriam esse convenit gloriosam.Eodem tempore Serenianus ex duce, cuius ignavia populatam in Phoenice Celsen ante rettulimus, pulsatae maiestatis imperii reus iure postulatus ac lege, incertum qua potuit suffragatione absolvi, aperte convictus familiarem suum cum pileo, quo caput operiebat, incantato vetitis artibus ad templum misisse fatidicum, quaeritatum expresse an ei firmum portenderetur imperium, ut cupiebat, et cunctum.Equitis Romani autem esse filium criminis loco poni ab accusatoribus neque his iudicantibus oportuit neque defendentibus nobis. Nam quod de pietate dixistis, est quidem ista nostra existimatio, sed iudicium certe parentis; quid nos opinemur, audietis ex iuratis; quid parentes sentiant, lacrimae matris incredibilisque maeror, squalor patris et haec praesens maestitia, quam cernitis, luctusque declarat.', NOW(), 00000, '00000000'),
       ('Belgique - Suisse: Petkovic avance masqué', 'Une fois de plus, Vladimir Petkovic avance masqué. Le sélectionneur n\'a pas voulu préciser si son équipe évoluera comme le mois dernier à Leicester face à l\'Angleterre avec une défense à trois."Laissez-vous surprendre, répond le "Mister". Nous avons essayé plusieurs choses depuis le mois de septembre. Je me donne encore un délai de réflexion avant de trancher vendredi à midi." On n\'est toutefois pas obligé de le croire, de penser qu\'il hésiterait encore à quelques heures de défier l\'une des meilleures équipes du monde.Vladimir Petkovic se félicite, par ailleurs, du travail accompli depuis lundi. L\'accent est toujours mis sur la vitesse. Il entend que son équipe puisse désormais évoluer sur un tempo plus élevé. "A nous de faire un pas de plus", souligne pour sa part Granit Xhaka.', NOW(), 11, '111111111111111111111111111'),
       ('Belgique: Problèmes mineurs sur quatre réacteurs nucléaires ', ' BRUXELLES (Reuters) - Le gendarme nucléaire belge a déclaré vendredi que les dégradations constatées dans les bunkers en béton entourant quatre des sept réacteurs nucléaires du pays correspondaient à une "anomalie", soit le niveau le moins grave dans l\'échelle des problèmes du régulateur.Dans un communiqué, l\'Agence fédérale de contrôle nucléaire (AFCN) précise que ces "anomalies" dans les bunkers de Doel 3, Doel 4, Tihange 2 et Tihange 3, repérées en octobre 2017, n\'ont eu "aucun impact sur la population, les travailleurs et l\'environnement".L\'échelle Ines du régulateur, "destinée à faciliter la perception de l\'importance d\'un événement impliquant des sources de rayonnements ionisants", compte sept niveaux allant du niveau 1 (anomalie) au 7 (accident majeur).La Belgique se trouve devant une possible et inédite situation de pénurie d\'électricité à l\'approche des mois d\'hiver, avec seulement un des sept réacteurs nucléaires du pays, tous exploités par Engie, prévu pour être pleinement opérationnel en novembre.Pour faire face à cet problème, le directeur général du gestionnaire de réseau Elia Chris Peeters a dit au début du mois que la Belgique pourrait importer 1.000 mégawatts d\'électricité de France.', NOW(), 2222, '2222222222222222'),
       ('Droits des citoyens – ou absence de droits', 'Pour ces gens, un Brexit sans accord pourrait être vu comme le pire des scénarios, car il les plongerait dans une totale incertitude, sans base légale quant à leur résidence. La Suisse n’est pas membre de l’UE, mais le droit des citoyens de l’Union à habiter et à travailler en Suisse est réglé par le même accord qu’avec les pays de l’UE – l’accord de libre-circulation -, dont la Grande Bretagne ne ferait plus partie après le Brexit. Il faudrait donc négocier un nouvel accord bilatéral entre les deux pays.À fin septembre, la bibliothèque de la Chambre des Communes a publié une liste des incertitudes résultant du Brexit. Les droits des expatriés britanniques y sont notamment décrits comme n’étant que «partiellement connus».', NOW(), 444, '44444444444444444444444444'),
       ('Que signifierait un Brexit «dur» pour les Britanniques résidant en Suisse?', 'Si le Royaume Uni et l’UE devaient se séparer sans être parvenus à un accord, qu’arriverait-il aux sujets de Sa Gracieuse Majesté résidant en Suisse. À six mois de l’échéance, aucun accord n’a non plus été passé entre Berne et Londres, si bien que les expatriés britanniques sont dans l’incertitude la plus complète.Un accord-cadre entre Londres et Bruxelles était censé être conclu cet automne. Or la pendule tourne et personne ne sait ce qui va se passer dans les prochaines semaines. La proposition de la première ministre Theresa May a été déclarée inapplicable par les leaders de l’Union réunis à Salzbourg à fin septembre, et même les politiciens britanniques sont loin d’être unanimes sur leur soutien ou non à la proposition.', NOW(), 333, '333333333333333333');
 
INSERT INTO tbUserProject (userId, projectId) 
VALUES ('1','1'),
       ('1','2'),
       ('2','3'),
       ('3','4'),
       ('5','5');
